export const themes = {
  elegant: {
    name: "Элегантный",
    bg: "bg-gradient-to-br from-gray-50 to-gray-100",
    text: "text-gray-900",
    button:
      "px-10 py-5 bg-gray-900 text-white rounded-none border-2 border-gray-900 hover:bg-gray-800 shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-300 font-serif uppercase tracking-wider",
    accent: "text-gray-700",
    border: "border-gray-300",
    card: "bg-white/95 backdrop-blur-sm border-2 border-gray-200 shadow-2xl rounded-none",
    photoFrame:
      "rounded-none shadow-2xl border-4 border-gray-300 hover:border-gray-400 transition-all duration-500",
    font: "font-serif tracking-wide",
    titleFont: "font-serif font-light tracking-widest",
    titleSize: "text-4xl md:text-6xl",
    subtitleSize: "text-lg md:text-xl font-light tracking-wide",
    bodySize: "text-lg md:text-xl leading-relaxed",
    animation: "fade-up",
    gradient: "bg-gradient-to-r from-gray-800 to-gray-900",
    divider:
      "border-t-2 border-gray-300 relative before:absolute before:top-0 before:left-1/2 before:transform before:-translate-x-1/2 before:-translate-y-1/2 before:bg-gray-100 before:px-4 before:text-gray-700",
    dividerStyle: "classic",
    cardShape: "rectangular",
    buttonShape: "sharp",
  },
  romantic: {
    name: "Романтический",
    bg: "bg-gradient-to-br from-rose-100 via-pink-50 to-rose-100",
    text: "text-rose-900",
    button:
      "px-12 py-6 bg-gradient-to-r from-rose-600 to-pink-600 text-white rounded-full hover:from-rose-700 hover:to-pink-700 shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-300 font-serif italic",
    accent: "text-rose-700",
    border: "border-rose-300",
    card: "bg-white/80 backdrop-blur-sm border border-rose-200 shadow-xl rounded-3xl",
    photoFrame:
      "rounded-full shadow-2xl border-8 border-rose-300 hover:border-rose-400 transition-all duration-500 transform hover:rotate-3",
    font: "font-serif italic",
    titleFont: "font-serif italic font-normal",
    titleSize: "text-4xl md:text-5xl",
    subtitleSize: "text-lg md:text-xl italic",
    bodySize: "text-lg md:text-xl leading-loose font-light",
    animation: "fade-up",
    gradient: "bg-gradient-to-r from-rose-600 to-pink-600",
    divider:
      "relative flex items-center justify-center py-6 before:content-['♥'] before:absolute before:bg-rose-100 before:text-rose-600 before:text-2xl before:px-3",
    dividerStyle: "hearts",
    cardShape: "rounded",
    buttonShape: "pill",
  },
  modern: {
    name: "Современный",
    bg: "bg-gradient-to-br from-slate-900 via-gray-900 to-black",
    text: "text-white",
    button:
      "px-10 py-5 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-lg hover:from-blue-700 hover:to-cyan-700 shadow-lg hover:shadow-cyan-500/25 transform hover:scale-105 transition-all duration-300 font-mono uppercase tracking-widest",
    accent: "text-cyan-400",
    border: "border-slate-600",
    card: "bg-white/5 backdrop-blur-xl border border-white/10 shadow-2xl rounded-2xl",
    photoFrame:
      "rounded-2xl shadow-2xl border border-cyan-400/30 hover:border-cyan-400/60 transition-all duration-500 transform hover:scale-105 hover:rotate-1",
    font: "font-mono font-light",
    titleFont: "font-mono font-thin tracking-widest",
    titleSize: "text-4xl md:text-6xl",
    subtitleSize: "text-lg md:text-xl font-light tracking-wide",
    bodySize: "text-base md:text-lg leading-relaxed font-light",
    animation: "slide-up",
    gradient: "bg-gradient-to-r from-blue-600 to-cyan-600",
    divider:
      "border-t border-cyan-400/30 relative before:absolute before:top-0 before:left-0 before:right-0 before:h-px before:bg-gradient-to-r before:from-transparent before:via-cyan-400 before:to-transparent",
    dividerStyle: "neon",
    cardShape: "modern",
    buttonShape: "rounded",
  },
  luxury: {
    name: "Роскошный",
    bg: "bg-gradient-to-br from-amber-50 via-yellow-50 to-amber-100",
    text: "text-amber-950",
    button:
      "px-12 py-6 bg-gradient-to-r from-yellow-600 via-amber-600 to-yellow-700 text-white rounded-full hover:from-yellow-700 hover:via-amber-700 hover:to-yellow-800 shadow-2xl hover:shadow-amber-500/50 transform hover:scale-105 transition-all duration-300 font-serif font-bold tracking-wide",
    accent: "text-amber-700",
    border: "border-yellow-400",
    card: "bg-gradient-to-br from-white/95 to-yellow-50/95 backdrop-blur-sm border-2 border-yellow-300 shadow-2xl rounded-lg relative before:absolute before:inset-0 before:border-2 before:border-yellow-400/20 before:rounded-lg",
    photoFrame:
      "rounded-xl shadow-2xl border-4 border-yellow-400 hover:border-yellow-500 transition-all duration-500 transform hover:-rotate-2 hover:scale-105 relative before:absolute before:-inset-1 before:border-2 before:border-yellow-300/50 before:rounded-xl",
    font: "font-serif font-medium",
    titleFont: "font-serif font-bold tracking-wider",
    titleSize: "text-4xl md:text-5xl",
    subtitleSize: "text-xl md:text-2xl font-semibold tracking-wide",
    bodySize: "text-base md:text-lg leading-relaxed font-medium",
    animation: "zoom-in",
    gradient: "bg-gradient-to-r from-yellow-600 via-amber-600 to-yellow-700",
    divider:
      "border-t-4 border-double border-yellow-400 relative before:absolute before:top-0 before:left-1/2 before:transform before:-translate-x-1/2 before:-translate-y-1/2 before:bg-yellow-50 before:px-6 before:text-yellow-700 before:text-xl before:font-serif",
    dividerStyle: "ornate",
    cardShape: "luxury",
    buttonShape: "elegant",
  },
  nature: {
    name: "Природный",
    bg: "bg-gradient-to-br from-green-50 via-emerald-50 to-green-100",
    text: "text-green-900",
    button:
      "px-10 py-5 bg-gradient-to-r from-green-700 to-emerald-700 text-white rounded-2xl hover:from-green-800 hover:to-emerald-800 shadow-lg hover:shadow-green-500/25 transform hover:scale-105 transition-all duration-300 font-sans font-medium",
    accent: "text-emerald-700",
    border: "border-green-400",
    card: "bg-white/85 backdrop-blur-sm border-2 border-green-300 shadow-xl rounded-3xl relative before:absolute before:inset-0 before:rounded-3xl before:bg-gradient-to-br before:from-green-100/20 before:to-transparent",
    photoFrame:
      "rounded-3xl shadow-2xl border-4 border-green-400 hover:border-emerald-500 transition-all duration-500 transform hover:rotate-2 hover:scale-105",
    font: "font-sans font-normal",
    titleFont: "font-sans font-light tracking-wide",
    titleSize: "text-3xl md:text-4xl",
    subtitleSize: "text-lg md:text-xl font-light",
    bodySize: "text-base md:text-lg leading-relaxed",
    animation: "fade-left",
    gradient: "bg-gradient-to-r from-green-700 to-emerald-700",
    divider:
      "relative flex items-center justify-center py-6 before:content-['🌿'] before:absolute before:bg-green-50 before:text-green-600 before:text-2xl before:px-4 before:rounded-full",
    dividerStyle: "natural",
    cardShape: "organic",
    buttonShape: "soft",
  },
  vintage: {
    name: "Винтажный",
    bg: "bg-gradient-to-br from-amber-100 via-orange-50 to-amber-200",
    text: "text-amber-900",
    button:
      "px-8 py-4 bg-amber-800 text-amber-50 rounded-sm hover:bg-amber-900 shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-300 font-serif font-bold uppercase tracking-widest border-2 border-amber-900",
    accent: "text-orange-700",
    border: "border-amber-400",
    card: "bg-gradient-to-br from-amber-50/95 to-orange-50/95 backdrop-blur-sm border-4 border-double border-amber-400 shadow-2xl rounded-none relative before:absolute before:inset-2 before:border before:border-amber-300 before:rounded-none",
    photoFrame:
      "rounded-none shadow-2xl border-8 border-double border-amber-500 hover:border-orange-500 transition-all duration-500 sepia hover:sepia-0",
    font: "font-serif font-normal",
    titleFont: "font-serif font-black tracking-wider",
    titleSize: "text-4xl md:text-6xl",
    subtitleSize: "text-lg md:text-xl font-bold uppercase tracking-widest",
    bodySize: "text-base md:text-lg leading-normal font-medium",
    animation: "fade-up",
    gradient: "bg-gradient-to-r from-amber-800 to-orange-800",
    divider:
      "border-t-4 border-double border-amber-600 relative before:absolute before:top-0 before:left-1/2 before:transform before:-translate-x-1/2 before:-translate-y-1/2 before:bg-amber-100 before:px-8 before:text-amber-800 before:text-2xl before:font-serif before:content-['❦']",
    dividerStyle: "vintage",
    cardShape: "classic",
    buttonShape: "vintage",
  },
  minimalist: {
    name: "Минималистский",
    bg: "bg-white",
    text: "text-gray-900",
    button:
      "px-8 py-3 bg-transparent text-gray-900 border border-gray-900 hover:bg-gray-900 hover:text-white transition-all duration-300 font-sans font-light uppercase tracking-[0.2em]",
    accent: "text-gray-600",
    border: "border-gray-200",
    card: "bg-white border border-gray-100 shadow-sm rounded-none",
    photoFrame:
      "rounded-none shadow-sm border border-gray-200 hover:shadow-md transition-all duration-500",
    font: "font-sans font-light",
    titleFont: "font-sans font-thin tracking-[0.3em]",
    titleSize: "text-4xl md:text-6xl",
    subtitleSize: "text-lg md:text-xl font-light tracking-[0.2em]",
    bodySize: "text-sm md:text-base leading-loose font-light",
    animation: "fade-up",
    gradient: "bg-gray-900",
    divider: "border-t border-gray-200",
    dividerStyle: "minimal",
    cardShape: "clean",
    buttonShape: "minimal",
  },
  festive: {
    name: "Праздничный",
    bg: "bg-gradient-to-br from-purple-100 via-pink-100 to-red-100",
    text: "text-purple-900",
    button:
      "px-10 py-5 bg-gradient-to-r from-purple-600 via-pink-600 to-red-600 text-white rounded-full hover:from-purple-700 hover:via-pink-700 hover:to-red-700 shadow-lg hover:shadow-xl transform hover:scale-110 hover:rotate-1 transition-all duration-300 font-sans font-bold animate-pulse",
    accent: "text-pink-700",
    border: "border-purple-300",
    card: "bg-gradient-to-br from-white/90 to-purple-50/90 backdrop-blur-sm border-2 border-purple-200 shadow-xl rounded-2xl relative before:absolute before:-inset-1 before:bg-gradient-to-r before:from-purple-400 before:via-pink-400 before:to-red-400 before:rounded-2xl before:-z-10 before:blur-sm",
    photoFrame:
      "rounded-2xl shadow-2xl border-4 border-purple-400 hover:border-pink-400 transition-all duration-500 transform hover:scale-110 hover:rotate-3 relative before:absolute before:-inset-2 before:bg-gradient-to-r before:from-purple-400 before:via-pink-400 before:to-red-400 before:rounded-2xl before:-z-10 before:blur-md before:animate-pulse",
    font: "font-sans font-semibold",
    titleFont: "font-sans font-black tracking-wide",
    titleSize: "text-4xl md:text-5xl",
    subtitleSize: "text-lg md:text-xl font-bold",
    bodySize: "text-lg md:text-xl leading-relaxed font-semibold",
    animation: "bounce-in",
    gradient: "bg-gradient-to-r from-purple-600 via-pink-600 to-red-600",
    divider:
      "relative flex items-center justify-center py-6 before:content-['🎉'] before:absolute before:bg-gradient-to-r before:from-purple-100 before:to-pink-100 before:text-purple-600 before:text-3xl before:px-6 before:rounded-full before:animate-bounce",
    dividerStyle: "festive",
    cardShape: "party",
    buttonShape: "festive",
  },
  cosmic: {
    name: "Космический",
    bg: "bg-gradient-to-br from-indigo-900 via-purple-900 to-black",
    text: "text-white",
    button:
      "px-12 py-6 bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white rounded-full hover:from-indigo-700 hover:via-purple-700 hover:to-pink-700 shadow-lg hover:shadow-purple-500/50 transform hover:scale-105 transition-all duration-300 font-mono uppercase tracking-widest relative before:absolute before:inset-0 before:rounded-full before:bg-gradient-to-r before:from-indigo-400 before:via-purple-400 before:to-pink-400 before:-z-10 before:blur-md before:animate-pulse",
    accent: "text-purple-300",
    border: "border-purple-500",
    card: "bg-black/50 backdrop-blur-xl border border-purple-500/30 shadow-2xl rounded-3xl relative before:absolute before:inset-0 before:rounded-3xl before:bg-gradient-to-br before:from-indigo-500/10 before:via-purple-500/10 before:to-pink-500/10",
    photoFrame:
      "rounded-3xl shadow-2xl border-2 border-purple-500/50 hover:border-purple-400 transition-all duration-500 transform hover:scale-105 hover:rotate-1 relative before:absolute before:-inset-2 before:bg-gradient-to-r before:from-indigo-500/20 before:via-purple-500/20 before:to-pink-500/20 before:rounded-3xl before:-z-10 before:blur-lg",
    font: "font-mono font-light",
    titleFont: "font-mono font-thin tracking-[0.3em]",
    titleSize: "text-4xl md:text-6xl",
    subtitleSize: "text-lg md:text-xl font-light tracking-[0.2em]",
    bodySize: "text-base md:text-lg leading-relaxed font-light",
    animation: "zoom-in",
    gradient: "bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600",
    divider:
      "relative flex items-center justify-center py-8 before:content-['✨'] before:absolute before:text-purple-400 before:text-3xl before:animate-pulse after:absolute after:inset-0 after:bg-gradient-to-r after:from-transparent after:via-purple-500/20 after:to-transparent after:h-px after:top-1/2",
    dividerStyle: "cosmic",
    cardShape: "futuristic",
    buttonShape: "cosmic",
  },
  bohemian: {
    name: "Богемный",
    bg: "bg-gradient-to-br from-orange-100 via-red-100 to-pink-100",
    text: "text-orange-900",
    button:
      "px-10 py-5 bg-gradient-to-r from-orange-600 via-red-600 to-pink-600 text-white rounded-2xl hover:from-orange-700 hover:via-red-700 hover:to-pink-700 shadow-lg hover:shadow-xl transform hover:scale-105 hover:-rotate-1 transition-all duration-300 font-serif italic font-semibold",
    accent: "text-red-700",
    border: "border-orange-300",
    card: "bg-gradient-to-br from-white/85 to-orange-50/85 backdrop-blur-sm border-2 border-orange-300 shadow-xl rounded-[2rem] relative before:absolute before:inset-0 before:rounded-[2rem] before:bg-gradient-to-br before:from-orange-200/20 before:via-red-200/20 before:to-pink-200/20",
    photoFrame:
      "rounded-[2rem] shadow-2xl border-4 border-orange-400 hover:border-red-400 transition-all duration-500 transform hover:rotate-3 hover:scale-105 relative before:absolute before:-inset-2 before:bg-gradient-to-r before:from-orange-400/30 before:via-red-400/30 before:to-pink-400/30 before:rounded-[2rem] before:-z-10 before:blur-sm",
    font: "font-serif italic",
    titleFont: "font-serif italic font-semibold tracking-wide",
    titleSize: "text-4xl md:text-5xl",
    subtitleSize: "text-lg md:text-xl italic font-medium",
    bodySize: "text-lg md:text-xl leading-loose italic",
    animation: "fade-right",
    gradient: "bg-gradient-to-r from-orange-600 via-red-600 to-pink-600",
    divider:
      "relative flex items-center justify-center py-6 before:content-['🌸'] before:absolute before:bg-gradient-to-r before:from-orange-100 before:to-pink-100 before:text-orange-600 before:text-2xl before:px-4 before:rounded-full after:absolute after:inset-0 after:border-t-2 after:border-dashed after:border-orange-300 after:top-1/2",
    dividerStyle: "bohemian",
    cardShape: "artistic",
    buttonShape: "bohemian",
  },
};

export const themeNames = Object.keys(themes) as Array<keyof typeof themes>;
